print("a)")
print("  *  ")
print(" *** ")
print("*****")
print(" *** ")
print("  *  ")
print("b)")
print("*****")
print("** **")
print("* * *")
print("** **")
print("*****")
print("c)")
print("   *******   ")
print(" *         * ")
print("*   Hello   *")
print(" *         * ")
print("   *******   ")
